Repository haskell-beginners-2022/exercises, pull requests merged in 2022-01, with the labels that each got.

#8 [#7] Add exercises and tests for Lecture 1
  Makefile
  README.md
  src/Lecture1.hs
  src/Lecture2.hs
  src/Lecture3.hs
  src/Lecture4.hs
  test/Test/Lecture1.hs
Labels: exercises, tests

#12 Add exercises and tests to Lecture 2
  .github/workflows/ci.yml
  Makefile
  exercises.cabal
  src/Lecture2.hs
  test/DoctestLecture2.hs
  test/Spec.hs
  test/Test/Lecture1.hs
  test/Test/Lecture2.hs
Labels: exercises, tests

#15 [#10] Add Lecture 3 exercises and tests
  .github/workflows/ci.yml
  Makefile
  cabal.project
  exercises.cabal
  src/Lecture3.hs
  test/DoctestLecture3.hs
  test/Spec.hs
  test/Test/Lecture3.hs
Labels: exercises, tests

#16 Fixed typos
  README.md
Labels: documentation

#21 Fix typo
  test/Test/Lecture1.hs
Labels: tests

#22 Add subString negative to zero test
  test/Test/Lecture1.hs
Labels: tests

#24 Add Stack support
  .github/workflows/ci.yml
  README.md
  stack.yaml
Labels: dependencies, CI, tests

#26 Fix: Incorrect test case for `substring` function
  test/Test/Lecture1.hs
Labels: tests

#27 Add more edge cases tests to subString
  test/Test/Lecture1.hs
Labels: tests

#38 Added a new testcase for lecture one substring test
  test/Test/Lecture1.hs
Labels: tests, lecture1

#43 Add tests on infinite lists for Lecture 2
  test/Test/Lecture2.hs
Labels: tests, lecture2

#47 Clarify that hard challenges are extra
  src/Lecture2.hs
Labels: documentation, lecture2

#49 Set UTF-8 encoding in tests
  test/Spec.hs
Labels: tests

#55 Add Lecture 4 exercises and tests
  .github/workflows/ci.yml
  Makefile
  app/Main.hs
  exercises.cabal
  src/Lecture4.hs
  test/Spec.hs
  test/Test/Lecture4.hs
  test/gen/Main.hs
  test/products.csv
Labels: tests, lecture4

#53 Add comments to indicate where imports can be added
  src/Lecture1.hs
  src/Lecture2.hs
  src/Lecture3.hs
Labels: documentation, tests
