Repository haskell-beginners-2022/exercises, pull requests merged in 2022-10, with the labels that each got.

#83 Fix typos in Lesson 2
  src/Lecture2.hs
Labels: documentation, hackotberfest-accepted

#86 Fix small typo
  src/Lecture1.hs
Labels: documentation

#90 Fix small typo
  src/Lecture2.hs
Labels: documentation, hackotberfest-accepted

#91 Fix small typos
  src/Lecture4.hs
Labels: hackotberfest-accepted
