Repository haskell-beginners-2022/exercises, pull requests merged in 2022-02, with the labels that each got.

#58 Fix huge file generator
  test/gen/Main.hs
Labels: bug, tests

#59 Documentation and test improvements to the course
  README.md
  src/Lecture4.hs
  test/Test/Lecture3.hs
Labels: documentation, tests

#60 Add big.csv to .gitignore
  .gitignore
Labels: enhancement

#62 Lecture 4 clarifications and suggestions
  src/Lecture4.hs
Labels: documentation, lecture4

#64 Add tests to `Semigroup`s
  test/Test/Lecture3.hs
  test/Test/Lecture4.hs
Labels: tests, lecture3
